### ISSUE TITLE
Can't find username by secondary email address

### ISSUE THREAD

**Issue by maxkueng** [beaugunderson/github-current-user#9]
My primary email address in my GitHub is the one I use just for receiving notifications. The one I use for commits (the one in my `.gitconfig`) is listed as a secondary email address.

It can't seem to find my username based on my secondary email address.

```
$ DEBUG=* github-current-user
  ghsign SSH_AUTH_SOCK +0ms /tmp/ssh-fR2░░░░░░/agent.5380
  github-current-user email from .gitconfig: me@m░░░░░░░░░░░ +92ms
Could not verify you [Error: Couldn't find a username for the supplied email]
```

![ghemail](https://cloud.githubusercontent.com/assets/168709/8096630/95c37336-0fd9-11e5-8686-8fe680c419e7.png)

**Comment by max-mapper** [comment]
yea I don't think github indexes by anything other than the primary email
